mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF359YOQ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/neuronalstemcell_ENCFF359YOQ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF717MIN.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/adiposetissue_ENCFF717MIN.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF588TQX.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/sigmoidcolon_ENCFF588TQX.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF268XDH.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/stomach_ENCFF268XDH.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF081DYZ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/aorta_ENCFF081DYZ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF199EFU.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/pancreas_ENCFF199EFU.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF746WLK.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/CD8positivealphabetaTcell_ENCFF746WLK.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF740OFO.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/H1_ENCFF740OFO.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF441FVJ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/esophagus_ENCFF441FVJ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF738KXI.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesendoderm_ENCFF738KXI.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF011JJG.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesenchymalstemcell_ENCFF011JJG.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF489LAR.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/endodermalcell_ENCFF489LAR.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF677DKS.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/psoasmuscle_ENCFF677DKS.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF365DFR.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/H1_ENCFF365DFR.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF985MTW.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF985MTW.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF148VCG.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF148VCG.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF050JVY.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/sigmoidcolon_ENCFF050JVY.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF093GMX.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/endodermalcell_ENCFF093GMX.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF251YUZ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/esophagus_ENCFF251YUZ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF317PIS.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesenchymalstemcell_ENCFF317PIS.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF107QNN.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesodermalcell_ENCFF107QNN.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF137MXA.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/trophoblastcell_ENCFF137MXA.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF677DAD.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/trophoblastcell_ENCFF677DAD.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF549FQD.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF549FQD.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF370OWM.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF370OWM.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF905ZXT.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/neuronalstemcell_ENCFF905ZXT.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF584GAJ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/smallintestine_ENCFF584GAJ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF717MVQ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/spleen_ENCFF717MVQ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF894PUN.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/smallintestine_ENCFF894PUN.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF864QLZ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/aorta_ENCFF864QLZ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF028PIJ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesendoderm_ENCFF028PIJ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF716ABE.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/CD8positivealphabetaTcell_ENCFF716ABE.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF056CIU.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/stomach_ENCFF056CIU.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF491UPQ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/adiposetissue_ENCFF491UPQ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF686CNC.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF686CNC.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF154POQ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ectodermalcell_ENCFF154POQ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF738TTD.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/psoasmuscle_ENCFF738TTD.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF597BAH.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/CD4positivealphabetaTcell_ENCFF597BAH.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF918SPI.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/spleen_ENCFF918SPI.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF091OZL.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/mesodermalcell_ENCFF091OZL.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF208TSZ.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/CD4positivealphabetaTcell_ENCFF208TSZ.bam
mv /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/ENCFF085TWC.bam /home/dhthutrang/ENCODE/mRNA_seq/raw_data/1/pancreas_ENCFF085TWC.bam
