python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_aorta -c majiq_config/adiposetissue_aorta.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_CD4positivealphabetaTcell -c majiq_config/adiposetissue_CD4positivealphabetaTcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_CD8positivealphabetaTcell -c majiq_config/adiposetissue_CD8positivealphabetaTcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_ectodermalcell -c majiq_config/adiposetissue_ectodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_endodermalcell -c majiq_config/adiposetissue_endodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_esophagus -c majiq_config/adiposetissue_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_H1 -c majiq_config/adiposetissue_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_mesenchymalstemcell -c majiq_config/adiposetissue_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_mesendoderm -c majiq_config/adiposetissue_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_mesodermalcell -c majiq_config/adiposetissue_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_neuronalstemcell -c majiq_config/adiposetissue_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_pancreas -c majiq_config/adiposetissue_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_psoasmuscle -c majiq_config/adiposetissue_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_sigmoidcolon -c majiq_config/adiposetissue_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_smallintestine -c majiq_config/adiposetissue_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_spleen -c majiq_config/adiposetissue_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_stomach -c majiq_config/adiposetissue_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/adiposetissue_trophoblastcell -c majiq_config/adiposetissue_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_CD4positivealphabetaTcell -c majiq_config/aorta_CD4positivealphabetaTcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_CD8positivealphabetaTcell -c majiq_config/aorta_CD8positivealphabetaTcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_ectodermalcell -c majiq_config/aorta_ectodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_endodermalcell -c majiq_config/aorta_endodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_esophagus -c majiq_config/aorta_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_H1 -c majiq_config/aorta_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_mesenchymalstemcell -c majiq_config/aorta_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_mesendoderm -c majiq_config/aorta_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_mesodermalcell -c majiq_config/aorta_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_neuronalstemcell -c majiq_config/aorta_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_pancreas -c majiq_config/aorta_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_psoasmuscle -c majiq_config/aorta_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_sigmoidcolon -c majiq_config/aorta_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_smallintestine -c majiq_config/aorta_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_spleen -c majiq_config/aorta_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_stomach -c majiq_config/aorta_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/aorta_trophoblastcell -c majiq_config/aorta_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_CD8positivealphabetaTcell -c majiq_config/CD4positivealphabetaTcell_CD8positivealphabetaTcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_ectodermalcell -c majiq_config/CD4positivealphabetaTcell_ectodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_endodermalcell -c majiq_config/CD4positivealphabetaTcell_endodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_esophagus -c majiq_config/CD4positivealphabetaTcell_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_H1 -c majiq_config/CD4positivealphabetaTcell_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_mesenchymalstemcell -c majiq_config/CD4positivealphabetaTcell_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_mesendoderm -c majiq_config/CD4positivealphabetaTcell_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_mesodermalcell -c majiq_config/CD4positivealphabetaTcell_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_neuronalstemcell -c majiq_config/CD4positivealphabetaTcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_pancreas -c majiq_config/CD4positivealphabetaTcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_psoasmuscle -c majiq_config/CD4positivealphabetaTcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_sigmoidcolon -c majiq_config/CD4positivealphabetaTcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_smallintestine -c majiq_config/CD4positivealphabetaTcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_spleen -c majiq_config/CD4positivealphabetaTcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_stomach -c majiq_config/CD4positivealphabetaTcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD4positivealphabetaTcell_trophoblastcell -c majiq_config/CD4positivealphabetaTcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_ectodermalcell -c majiq_config/CD8positivealphabetaTcell_ectodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_endodermalcell -c majiq_config/CD8positivealphabetaTcell_endodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_esophagus -c majiq_config/CD8positivealphabetaTcell_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_H1 -c majiq_config/CD8positivealphabetaTcell_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_mesenchymalstemcell -c majiq_config/CD8positivealphabetaTcell_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_mesendoderm -c majiq_config/CD8positivealphabetaTcell_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_mesodermalcell -c majiq_config/CD8positivealphabetaTcell_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_neuronalstemcell -c majiq_config/CD8positivealphabetaTcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_pancreas -c majiq_config/CD8positivealphabetaTcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_psoasmuscle -c majiq_config/CD8positivealphabetaTcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_sigmoidcolon -c majiq_config/CD8positivealphabetaTcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_smallintestine -c majiq_config/CD8positivealphabetaTcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_spleen -c majiq_config/CD8positivealphabetaTcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_stomach -c majiq_config/CD8positivealphabetaTcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/CD8positivealphabetaTcell_trophoblastcell -c majiq_config/CD8positivealphabetaTcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_endodermalcell -c majiq_config/ectodermalcell_endodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_esophagus -c majiq_config/ectodermalcell_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_H1 -c majiq_config/ectodermalcell_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_mesenchymalstemcell -c majiq_config/ectodermalcell_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_mesendoderm -c majiq_config/ectodermalcell_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_mesodermalcell -c majiq_config/ectodermalcell_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_neuronalstemcell -c majiq_config/ectodermalcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_pancreas -c majiq_config/ectodermalcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_psoasmuscle -c majiq_config/ectodermalcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_sigmoidcolon -c majiq_config/ectodermalcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_smallintestine -c majiq_config/ectodermalcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_spleen -c majiq_config/ectodermalcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_stomach -c majiq_config/ectodermalcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/ectodermalcell_trophoblastcell -c majiq_config/ectodermalcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_esophagus -c majiq_config/endodermalcell_esophagus.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_H1 -c majiq_config/endodermalcell_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_mesenchymalstemcell -c majiq_config/endodermalcell_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_mesendoderm -c majiq_config/endodermalcell_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_mesodermalcell -c majiq_config/endodermalcell_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_neuronalstemcell -c majiq_config/endodermalcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_pancreas -c majiq_config/endodermalcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_psoasmuscle -c majiq_config/endodermalcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_sigmoidcolon -c majiq_config/endodermalcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_smallintestine -c majiq_config/endodermalcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_spleen -c majiq_config/endodermalcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_stomach -c majiq_config/endodermalcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/endodermalcell_trophoblastcell -c majiq_config/endodermalcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_H1 -c majiq_config/esophagus_H1.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_mesenchymalstemcell -c majiq_config/esophagus_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_mesendoderm -c majiq_config/esophagus_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_mesodermalcell -c majiq_config/esophagus_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_neuronalstemcell -c majiq_config/esophagus_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_pancreas -c majiq_config/esophagus_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_psoasmuscle -c majiq_config/esophagus_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_sigmoidcolon -c majiq_config/esophagus_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_smallintestine -c majiq_config/esophagus_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_spleen -c majiq_config/esophagus_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_stomach -c majiq_config/esophagus_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/esophagus_trophoblastcell -c majiq_config/esophagus_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_mesenchymalstemcell -c majiq_config/H1_mesenchymalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_mesendoderm -c majiq_config/H1_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_mesodermalcell -c majiq_config/H1_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_neuronalstemcell -c majiq_config/H1_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_pancreas -c majiq_config/H1_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_psoasmuscle -c majiq_config/H1_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_sigmoidcolon -c majiq_config/H1_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_smallintestine -c majiq_config/H1_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_spleen -c majiq_config/H1_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_stomach -c majiq_config/H1_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/H1_trophoblastcell -c majiq_config/H1_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_mesendoderm -c majiq_config/mesenchymalstemcell_mesendoderm.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_mesodermalcell -c majiq_config/mesenchymalstemcell_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_neuronalstemcell -c majiq_config/mesenchymalstemcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_pancreas -c majiq_config/mesenchymalstemcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_psoasmuscle -c majiq_config/mesenchymalstemcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_sigmoidcolon -c majiq_config/mesenchymalstemcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_smallintestine -c majiq_config/mesenchymalstemcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_spleen -c majiq_config/mesenchymalstemcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_stomach -c majiq_config/mesenchymalstemcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesenchymalstemcell_trophoblastcell -c majiq_config/mesenchymalstemcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_mesodermalcell -c majiq_config/mesendoderm_mesodermalcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_neuronalstemcell -c majiq_config/mesendoderm_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_pancreas -c majiq_config/mesendoderm_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_psoasmuscle -c majiq_config/mesendoderm_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_sigmoidcolon -c majiq_config/mesendoderm_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_smallintestine -c majiq_config/mesendoderm_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_spleen -c majiq_config/mesendoderm_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_stomach -c majiq_config/mesendoderm_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesendoderm_trophoblastcell -c majiq_config/mesendoderm_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_neuronalstemcell -c majiq_config/mesodermalcell_neuronalstemcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_pancreas -c majiq_config/mesodermalcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_psoasmuscle -c majiq_config/mesodermalcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_sigmoidcolon -c majiq_config/mesodermalcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_smallintestine -c majiq_config/mesodermalcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_spleen -c majiq_config/mesodermalcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_stomach -c majiq_config/mesodermalcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/mesodermalcell_trophoblastcell -c majiq_config/mesodermalcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_pancreas -c majiq_config/neuronalstemcell_pancreas.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_psoasmuscle -c majiq_config/neuronalstemcell_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_sigmoidcolon -c majiq_config/neuronalstemcell_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_smallintestine -c majiq_config/neuronalstemcell_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_spleen -c majiq_config/neuronalstemcell_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_stomach -c majiq_config/neuronalstemcell_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/neuronalstemcell_trophoblastcell -c majiq_config/neuronalstemcell_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_psoasmuscle -c majiq_config/pancreas_psoasmuscle.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_sigmoidcolon -c majiq_config/pancreas_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_smallintestine -c majiq_config/pancreas_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_spleen -c majiq_config/pancreas_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_stomach -c majiq_config/pancreas_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/pancreas_trophoblastcell -c majiq_config/pancreas_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/psoasmuscle_sigmoidcolon -c majiq_config/psoasmuscle_sigmoidcolon.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/psoasmuscle_smallintestine -c majiq_config/psoasmuscle_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/psoasmuscle_spleen -c majiq_config/psoasmuscle_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/psoasmuscle_stomach -c majiq_config/psoasmuscle_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/psoasmuscle_trophoblastcell -c majiq_config/psoasmuscle_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/sigmoidcolon_smallintestine -c majiq_config/sigmoidcolon_smallintestine.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/sigmoidcolon_spleen -c majiq_config/sigmoidcolon_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/sigmoidcolon_stomach -c majiq_config/sigmoidcolon_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/sigmoidcolon_trophoblastcell -c majiq_config/sigmoidcolon_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/smallintestine_spleen -c majiq_config/smallintestine_spleen.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/smallintestine_stomach -c majiq_config/smallintestine_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/smallintestine_trophoblastcell -c majiq_config/smallintestine_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/spleen_stomach -c majiq_config/spleen_stomach.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/spleen_trophoblastcell -c majiq_config/spleen_trophoblastcell.txt
python3 $MAJIQ build /home/dhthutrang/ENCODE/refgen/majiq/hg38.ncbiRefSeq.gtf -j 8 -o majiq_build_res/stomach_trophoblastcell -c majiq_config/stomach_trophoblastcell.txt
