mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF359YOQ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/neuronalstemcell_ENCFF359YOQ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF717MIN.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/adiposetissue_ENCFF717MIN.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF588TQX.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/sigmoidcolon_ENCFF588TQX.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF268XDH.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/stomach_ENCFF268XDH.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF081DYZ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/aorta_ENCFF081DYZ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF199EFU.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/pancreas_ENCFF199EFU.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF746WLK.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/CD8positivealphabetaTcell_ENCFF746WLK.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF740OFO.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/H1_ENCFF740OFO.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF441FVJ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/esophagus_ENCFF441FVJ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF738KXI.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesendoderm_ENCFF738KXI.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF011JJG.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesenchymalstemcell_ENCFF011JJG.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF489LAR.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/endodermalcell_ENCFF489LAR.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF677DKS.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/psoasmuscle_ENCFF677DKS.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF365DFR.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/H1_ENCFF365DFR.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF985MTW.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF985MTW.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF148VCG.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF148VCG.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF050JVY.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/sigmoidcolon_ENCFF050JVY.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF093GMX.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/endodermalcell_ENCFF093GMX.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF251YUZ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/esophagus_ENCFF251YUZ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF317PIS.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesenchymalstemcell_ENCFF317PIS.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF107QNN.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesodermalcell_ENCFF107QNN.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF137MXA.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/trophoblastcell_ENCFF137MXA.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF677DAD.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/trophoblastcell_ENCFF677DAD.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF549FQD.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF549FQD.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF370OWM.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF370OWM.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF905ZXT.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/neuronalstemcell_ENCFF905ZXT.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF584GAJ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/smallintestine_ENCFF584GAJ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF717MVQ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/spleen_ENCFF717MVQ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF894PUN.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/smallintestine_ENCFF894PUN.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF864QLZ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/aorta_ENCFF864QLZ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF028PIJ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesendoderm_ENCFF028PIJ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF716ABE.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/CD8positivealphabetaTcell_ENCFF716ABE.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF056CIU.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/stomach_ENCFF056CIU.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF491UPQ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/adiposetissue_ENCFF491UPQ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF686CNC.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF686CNC.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF154POQ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ectodermalcell_ENCFF154POQ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF738TTD.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/psoasmuscle_ENCFF738TTD.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF597BAH.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/CD4positivealphabetaTcell_ENCFF597BAH.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF918SPI.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/spleen_ENCFF918SPI.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF091OZL.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/mesodermalcell_ENCFF091OZL.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF208TSZ.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/CD4positivealphabetaTcell_ENCFF208TSZ.sam
mv /home/dhthutrang/ENCODE/mRNA_seq/sam_files/ENCFF085TWC.sam /home/dhthutrang/ENCODE/mRNA_seq/sam_files/pancreas_ENCFF085TWC.sam
