## ---------------------------
##
## Script name: GO_analysis_methods.R
##
## Purpose of script: Methods for the gene enrichment analysis of epispliced genes
##
## Author: Trang Do
##
## Copyright (c) Trang Do, 2018
## Email: dhttrang@bioinformatik.uni-saarland.de
##
## ---------------------------
##
## Notes:
## - Description: This script contains the analyzing and plotting methods for the Gene Ontology Enrichment Analysis of
## epispliced genes identified in analysis_pipeline.R. 
## - Preceeding script: analysis_pipeline.R
## - Succeeding script: -
##
## ---------------------------

# ==== LOAD PACKAGES =====
library("clusterProfiler", quietly = TRUE)
library("org.Hs.eg.db", quietly = TRUE)
library("DOSE", quietly = TRUE)
library("data.table", quietly = TRUE)
library("viridis", quietly = TRUE)
library("ggplot2", quietly = TRUE)
library("ggraph", quietly = TRUE)
library("ggpubr", quietly = TRUE)
library("stringr", quietly = TRUE)
library("enrichplot", quietly = TRUE)
library("biomaRt", quietly = TRUE)


# ==== METHODS TO PERFORM GENE ONTOLOGY ENRICHMENT ANALYSIS (GOEA) =====
get_entrez_id <- function(gene_list) {
  #' Given a list of HGNC gene IDs, return the Entrez gene IDs mapped to the genes 
  #'
  #' @param gene_list a list of HGNC gene ids
  #' @return a list Entrez gene symbol
  #'

  entrez_gene_list <- AnnotationDbi::select(org.Hs.eg.db, keytype = "SYMBOL", multiVals = "list", 
                                            keys = gene_list, columns = c("ENTREZID", "SYMBOL"))

  return(entrez_gene_list[[2]])
}

run_GO_analysis <- function(result_list, sign = "none", universe_genes_entrez = universe_genes_entrez) {
  #' Given a list of Entrez gene IDs, perform GO Terms Enrichment Analysis using ClusterProfiler 
  #'
  #' GO Terms Enrichment Analysis is performed using epispliced genes against the background set of all human genes
  #' having either DEU or DHM events at the exon boundaries. 
  #' @param result_list the list storing analysed results from a dataset generated by post_analysis(). result_list 
  #' should be distinguished from "info" list. 
  #' @param sign "none" implies identifying the epispliced genes by comparing the absolute(DEU-DHM R-values) agaisnt an
  #' R-values threshold. "pos" and "neg" implies comparing only positive or negative R-values to the threshold.
  #' @param universe_genes_entrez the list of genes used as background for the GO Terms Enrichment Analysis
  #' @return a compareCluster object sotring analysis results
  #'
  
  biomartCacheClear()
  print("..... Compare GOenrichment clusters")

  if (sign == "pos")
    TSEGs_ = result_list[["TSEGs_pos"]]
  else if (sign == "neg")
    TSEGs_ = result_list[["TSEGs_neg"]]
  else if (sign == "none")
    TSEGs_ = result_list[['TSEGs']]

  TSEGs_ <- lapply(TSEGs_, function(x) unique(unlist(x)))
  gene_list_his <- lapply(TSEGs_, get_entrez_id)
  names(gene_list_his) <- histone_type_list

  # Perform GO Terms Enrichment Analysis
  GO_res <- compareCluster(
    geneCluster = gene_list_his, fun = "enrichGO", OrgDb = "org.Hs.eg.db", ont = "BP", qvalueCutoff = 1,
    pAdjustMethod = "none", readable = TRUE, universe = universe_genes_entrez
  )

  return(GO_res)
}


# ==== METHODS TO PLOT RESULTS FROM GENE ONTOLOGY ENRICHMENT ANALYSIS =====
pretify_GO_result <- function(annot_df, sign = "none", gene_ratio = 0.01) {
  #' Clean up and decorate the dataframe storing annotation terms for plotting purposes
  #'
  #' This function filters the dataframe by p-values or gene ratios, corrects spelling, transforms texts, etc.
  #' @param annot_df the dataframe in compareClusterResult object where GO terms are stored
  #' @param sign "none" implies identifying the epispliced genes by comparing the absolute(DEU-DHM R-values) agaisnt an
  #' R-values threshold. "pos" and "neg" implies comparing only positive or negative R-values to the threshold.
  #' @param gene_ratio the threshold for the ratio of gene in the background set being annotated to a certain GO term. 
  #' @return cleaned up dataframe
  #'
  
  annot_df$Categories <- "Cellular & Metabolic\nProcesses"
  annot_df$Categories[
    grep(pattern = "ossification|differentiation|imprint|mesenchyma|pattern|hear|Endoderm|size|devel|genesis|growth|morpho|matur|organiz|guidan|organel|anato|exten|synapse|assembly", 
         x = annot_df$Description, ignore.case = TRUE)] <- "Developmental\nProcesses"
  annot_df$Categories[grep("signal|transport|import|secret|export|exo|transmi", annot_df$Description, ignore.case = TRUE)] <- "Cell Signaling"
  
  annot_df$Description <- stringr::str_to_sentence(annot_df$Description)
  annot_df$Description <- gsub("h3-k9", "H3K9", annot_df$Description)
  annot_df$Description <- gsub("h3-k36", "H3K36", annot_df$Description)
  annot_df$Description <- gsub("h3-k4", "H3K4", annot_df$Description)
  annot_df$Description <- gsub("k63", "K63", annot_df$Description)
  annot_df$Description <- gsub("igg", "IGG", annot_df$Description)
  annot_df$Description <- gsub("Ncrna", "ncRNA", annot_df$Description)
  annot_df$Description <- gsub("Mirna", "miRNA", annot_df$Description)
  annot_df$Description <- gsub("gtpase", "GTPase", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub("Trna", "tRNA", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub("^Rna", "RNA", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub(" rna", " RNA", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub("^Dna", "DNA", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub("Snrna", "snRNA", annot_df$Description, ignore.case = TRUE)
  annot_df$Description <- gsub("membrane adhesion", "membrane -\n adhesion", annot_df$Description)
  annot_df$Description <- gsub("transport, golgi", "transport -\n golgi", annot_df$Description)

  if (sign == "none"){
    # Adjust the p-values 
    annot_df <- annot_df %>%
    dplyr::group_by(Categories) %>%
      dplyr::mutate(p.adjust = p.adjust(p.adjust, "fdr"))
    
    # Filter terms by  genes ratio
    annot_df$filter_gene_ratio <- sapply(annot_df$GeneRatio, function(x) {
      ratio <- strsplit(x, "/")[[1]]
      ratio <- as.numeric(ratio[1]) / as.numeric(ratio[2])
      })
    annot_df <- annot_df[annot_df$filter_gene_ratio > gene_ratio, ]
  } else {
    # For signed data, the p-values are adjusted based on in get_dotplot_signed_results() 
    # GeneRatio is used instead of filter_gene_ratio
    annot_df <- annot_df[annot_df$GeneRatio > gene_ratio, ]
  }
  
  annot_df$small_text <- sapply(annot_df$Description, function(x) length(strsplit(x, " ")[[1]]) >= 7)
  return(annot_df)
}

get_dotplot <- function(GO_result_list, gene_ratio = 0.01, filename) {
  #' Plot the enriched terms from GOEA to generate Figure 6(A-C). Only results from unsigned is used here (Otherwise 
  #' use get_dotplot_signed_results()). The GO terms are histone-specific.
  #'
  #' @param GO_result_list a list of GOEA results for both unsigned and signed methods. names(GO_result_list) should 
  #' include "none", "pos", "neg"
  #' @param gene_ratio the threshold for the ratio of gene in the background set being annotated to a certain GO term. 
  #' @param filename path to file where the plot should be saved
  #' @return enriched terms plot
  #'
  
  # Gather data for plotting
  CompareGOres <- GO_result_list[["none"]]
  CompareGOres@compareClusterResult <- pretify_GO_result(CompareGOres@compareClusterResult, gene_ratio)
  annot_df <- CompareGOres

  dotplot <- clusterProfiler::dotplot(annot_df, showCategory = 12) +
    facet_wrap(vars(Categories), nrow = 2, scales = "free") +
    scale_color_viridis(option = "D", name = "FDR-adjusted p-value") +
    scale_size(name = "Gene Ratio") +
    scale_y_discrete(guide = guide_axis(check.overlap = TRUE)) +
    theme(
      plot.title = element_text(size = 11, hjust = 0.5, face = "bold"), aspect.ratio = 2.5,
      axis.ticks = element_blank(), axis.title = element_blank(), panel.background = element_rect(fill = "white"),
      axis.text.x = element_text(colour = "black", size = 12, color = "black", angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(colour = "black", 
        size = ifelse(sapply(annot_df@compareClusterResult$small_text, function(x) length(grep("-", x)) > 0), 9, 12)),
      legend.position = c("right"), legend.box = "vertical", legend.margin = margin(),
      legend.justification = "top", strip.background = element_rect(fill = "#5D2ED2"),
      strip.text = element_text(color = "white", face = "bold", size = 11)
    )

  tiff(filename = filename, height = 12, width = 16, res = 400, units = "in")
  print(dotplot)
  dev.off()

  return(dotplot)
}

get_dotplot_signed_results <- function(GO_result_list, filename) {
  #' Plot the enriched terms from GOEA to generate Figure S4. Only results from signed is used here 
  #' (Otherwise use get_dotplot()). The GO terms are histone-specific.
  #'
  #' @param GO_result_list a list of GOEA results for both unsigned and signed methods. names(GO_result_list) should 
  #' include "none", "pos", "neg"
  #' @param filename path to file where the plot should be saved
  #' @return enriched terms plot
  #'
  
  # Gether data for plotting
  GO_res_neg <- GO_result_list[["neg"]]
  GO_res_neg@compareClusterResult$sign = "neg"
  GO_res_neg@compareClusterResult$p.adjust = p.adjust(GO_res_neg@compareClusterResult$p.adjust, "fdr")
  GO_res_pos <- GO_result_list[["pos"]]
  GO_res_pos@compareClusterResult$sign = "pos"
  GO_res_pos@compareClusterResult$p.adjust = p.adjust(GO_res_pos@compareClusterResult$p.adjust, "fdr")
  GO_res_neg <- fortify(GO_res_neg, showCategory = 12, split = "sign")
  GO_res_pos <- fortify(GO_res_pos, showCategory = 12, split = "sign")
  GO_res_df <- rbind(GO_res_neg, GO_res_pos)

  GO_res_df$Cluster = as.factor(unlist(lapply(
    as.character(GO_res_df$Cluster), function(x) strsplit(x, "\n", fixed = TRUE)[[1]][1]))
    )
  GO_res_df <- pretify_GO_result(GO_res_df, sign = "pos", gene_ratio = 0.02)
  GO_res_df <- GO_res_df[GO_res_df$p.adjust <= 0.05, ] 
  GO_res_df <- GO_res_df[order(GO_res_df$GeneRatio, decreasing = TRUE), ]

  dotplot <- ggplot(GO_res_df, aes_string(x = "Cluster", y = "Description", color = "sign", size = "GeneRatio")) +
    geom_point(aes(alpha = 0.3)) +
    guides(alpha = "none", color = guide_legend(override.aes = list(size = 10))) +
    facet_wrap(vars(Categories), ncol=3, scales = "free")  + 
    scale_color_manual(values = c("#63ACBE", "#EE442F"), name = "Correlation type", labels = c("Negative", "Positive")) +
    scale_size(name='Gene Ratio', range=c(3, 10)) + scale_y_discrete(guide = guide_axis(check.overlap = F)) +
    theme_dose() + 
    theme(
      plot.title = element_text(size = 10, hjust = 0.5, face = "bold"),
      axis.ticks = element_blank(), axis.title = element_blank(), axis.title.y = element_blank(),
      axis.text.x = element_text(colour="black", size = 12, color = 'black', angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(colour="black", size = 12, color = 'black'),
      panel.background = element_rect(fill = 'white'), legend.position = c("bottom"), legend.box = "horizontal",
      legend.margin = margin(), legend.text = element_text(size = 11),
      legend.title = element_text(size = 12, face="bold"), strip.background = element_rect(fill = "#5D2ED2"),
      strip.text = element_text(color = 'white', face = 'bold', size = 12)
    )

  tiff(filename, height = 8, width = 17, res = 400, units = "in")
  print(dotplot)
  dev.off()

  return(dotplot)
}

get_dotplot_all_epispliced_genes <- function(annot_df, filename){
  #' Plot the enriched terms from GOEA to generate Figure 6D. Only results from signed is used here (Otherwise use 
  #' get_dotplot()). The GO terms are not histone-specific.
  #'
  #' @param annot_df the dataframe retrieved from shinyGO after comparing all epispliced genes to the background genes.
  #' The columns should have names `Enrichment FDR`, `nGenes`, `Pathway Genes`, `Fold Enrichment`, `Pathway`, `URL`,
  #' `Genes`.
  #' @param filename path to file where the plot should be saved
  #' @return enriched terms plot
  #'
  
  annot_df$Pathway <- gsub("tyrosine kinase", "tyrosine-\nkinase", annot_df$Pathway)
  dotplot <- annot_df %>%
    dplyr::mutate(
      `Fold Enrichment` = as.numeric(`Fold Enrichment`),
      `Gene Ratio` = as.numeric(round(nGenes / `Pathway Genes`, 2))) %>%
    dplyr::arrange(`Fold Enrichment`) %>%
    dplyr::top_n(-20, `Enrichment FDR`) %>%
    dplyr::mutate(Pathway = factor(Pathway, levels = Pathway)) %>%
    ggplot(aes(x = `Fold Enrichment`, y = Pathway, col = -log(`Enrichment FDR`), size = `Gene Ratio`)) +
    geom_point() +
    geom_segment(aes(xend = 0, yend = Pathway), size = 1) +
    scale_color_viridis(option = "A", direction = -1, begin = 0.1, end = 0.9, 
                       name = expression(paste(-Log[10], FDR, sep = ""))) +
    scale_size(name = "Gene Ratio") + xlim(c(0, 1.9)) +
    theme(aspect.ratio = 2.5, axis.ticks = element_blank(), 
      axis.title.y = element_blank(), axis.title.x = element_text(face = "bold", size = 12),
      axis.text = element_text(size = 11, color = "black",
        lineheight = ifelse(sapply(df$Pathway, function(x) length(grep("-", x)) > 0), 1, 0.7)),
      panel.background = element_rect(fill = "white"), legend.position = "right", legend.box = "vertical"
    )

  tiff(filename = filename, height = 5, width = 9, res = 300, units = "in")
  print(dotplot)
  dev.off()

  return(dotplot)
}
